[server]
headless = true
address = "0.0.0.0"
port = 8501
fileWatcherType = "none"
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 10
enableStaticServing = true
maxMessageSize = 50

[browser]
gatherUsageStats = false

[client]
showErrorDetails = "none"
toolbarMode = "minimal"

[runner]
fastReruns = true
magicEnabled = false

[logger]
level = "error"
