"""Apply v1.0.4.1 evidence-chain templates to high-frequency events."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ONTOLOGY_PATH = ROOT / "rules" / "monthly_event_ontology.json"

COMMON_PALACE = {
    "year_branch": "年支偏向长辈、家庭背景、外部圈层和旧有关系。",
    "month_branch": "月支偏向事业平台、上级同事、客户组织和主业环境。",
    "day_branch": "日支偏向伴侣、合作方、一对一关系和居住状态。",
    "hour_branch": "时支偏向项目结果、副业、晚辈、长期规划和收尾事项。",
}

COMMON_CONFIDENCE = {
    "high": "至少命中4条证据，并且包含十神、喜用、宫位/大运流年中的至少3类依据。",
    "medium": "至少命中3条证据，但宫位或大运依据不足。",
    "low": "仅命中2条证据，只能作为轻度提醒，不进入优先Top事件。",
    "downgrade_reasons": [
        "忌神参与较重",
        "冲克过强",
        "证据只来自单一维度",
        "缺少宫位或现实场景支撑",
        "触发规则过于泛化",
        "反向条件被命中",
    ],
}


def base_chain(
    *,
    ten_god_basis: list[str],
    element_basis: list[str],
    branch_basis: list[str],
    source_ids: list[str],
    required_patterns: list[str],
    supporting_patterns: list[str],
    risk_patterns: list[str],
    palace_focus: list[str],
    positive: list[str],
    neutral: list[str],
    negative: list[str],
    anti_triggers: list[str],
    user_visible_basis: str,
    subtype_rules: dict | None = None,
) -> dict:
    palace = dict(COMMON_PALACE)
    palace["specific_focus"] = palace_focus
    return {
        "traditional_basis": {
            "ten_god_basis": ten_god_basis,
            "element_basis": element_basis,
            "branch_relation_basis": branch_basis,
            "shensha_basis": [
                "神煞只作为辅助加权，不单独决定事件。",
                "天乙贵人、桃花、驿马等只有在系统可靠实现时才进入触发证据。",
            ],
            "source_ids": source_ids,
        },
        "structure_basis": {
            "required_patterns": required_patterns,
            "supporting_patterns": supporting_patterns,
            "risk_patterns": risk_patterns,
        },
        "palace_basis": palace,
        "modern_mapping": {
            "positive_expression": positive,
            "neutral_expression": neutral,
            "negative_expression": negative,
        },
        "confidence_basis": COMMON_CONFIDENCE,
        "anti_triggers": anti_triggers,
        "user_visible_basis": user_visible_basis,
        "required_evidence_count": 2,
        "subtype_rules": subtype_rules or {},
    }


TEMPLATES = {
    "nobleman": base_chain(
        ten_god_basis=[
            "印星主帮助、保护、学习、资质、长辈、文书与平台资源。",
            "比劫主朋友、同辈、同行、同事、合伙人与团队。",
            "财星主客户、资源、订单、交易对象和转介绍。",
            "官杀主上级、领导、制度、职位、审批和权威人物。",
            "食伤主表达、饭局、内容输出、销售沟通和介绍传播。",
        ],
        element_basis=[
            "喜用五行参与时，帮助更容易转为正向资源。",
            "忌神五行参与时，帮助可能伴随条件、人情成本或落地反复。",
        ],
        branch_basis=[
            "年支被引动时，贵人更偏长辈、家庭、人脉圈层。",
            "月支被引动时，贵人更偏上级、平台、客户、组织资源。",
            "日支被引动时，贵人更偏伴侣、合作方或一对一关系。",
            "时支被引动时，贵人更偏项目、晚辈、副业和长期计划。",
        ],
        source_ids=["yuan_hai_zi_ping", "san_ming_tong_hui", "ming_li_tan_yuan"],
        required_patterns=["印星、喜用、宫位或大运流年至少两类共同出现。", "不能只凭一个贵人神煞下结论。"],
        supporting_patterns=["原局印星不弱", "当前流月为喜用", "大运或流年支持资源、人脉或平台"],
        risk_patterns=["忌神印星过重", "比劫夺财", "帮助伴随交换条件", "口头承诺多但落地慢"],
        palace_focus=["长辈、上级、客户、同辈、伴侣合作、平台或暗中帮助来源"],
        positive=["有人提醒关键问题", "获得牵线、引荐或资源入口", "专业人士给出可执行建议"],
        neutral=["有人提供信息，但真假和成本仍要自己判断", "帮助更像线索，不一定马上变结果"],
        negative=["帮助伴随人情压力或交换条件", "口头承诺多但落地较慢", "过度依赖他人导致节奏被牵着走"],
        anti_triggers=["忌神参与较重", "比劫夺财", "冲克过强", "只命中单一贵人神煞"],
        user_visible_basis="贵人不是简单说有人帮，而是看帮助来自哪类人、是否能落地、是否带条件。",
        subtype_rules={
            "长辈贵人": ["印星", "年支/家庭圈层被引动", "喜用相关"],
            "同辈贵人": ["比劫", "朋友同事同行信号", "不形成明显夺财"],
            "客户贵人": ["财星", "客户/订单/资源方", "转介绍或交易线索"],
            "上级贵人": ["官杀", "月支/事业平台", "审批、职位、领导支持"],
            "专业人士贵人": ["印星", "官印相生", "老师、顾问、律师、医生、证书文书"],
            "旧关系贵人": ["食伤或比劫", "旧友旧客户", "沟通传播带来线索"],
            "平台贵人": ["印星", "月支", "组织、平台、规则和系统支持"],
            "家庭贵人": ["印星", "年支", "家庭长辈或亲属支持"],
            "伴侣/合作贵人": ["日支", "夫妻宫/合作宫被引动", "一对一协作"],
            "暗中贵人": ["喜用", "印星", "未直接露面的帮助或信息"],
        },
    ),
    "payment": base_chain(
        ten_god_basis=["财星主钱款、客户、订单与现实回报。", "食伤主输出、服务、作品和交付，能推动财星落地。"],
        element_basis=["财星或食伤为喜用时，回款推进更顺。", "财星为忌或受冲时，容易出现拖延、折扣或反复确认。"],
        branch_basis=["月支引动多对应客户、项目和工作账期。", "日支引动多对应合作方、一对一结算。"],
        source_ids=["yuan_hai_zi_ping", "san_ming_tong_hui", "ming_li_tan_yuan"],
        required_patterns=["财星或食伤被引动", "喜忌、宫位或大运流年至少再命中一项"],
        supporting_patterns=["原局财星透出", "食伤能生财", "当前大运支持收入转化"],
        risk_patterns=["比劫较旺分财", "财星受冲", "合同票据不清"],
        palace_focus=["客户、项目、合同结算、合作方账期"],
        positive=["客户确认付款", "尾款推进", "旧账补齐或阶段结算"],
        neutral=["款项有消息但仍需走流程", "对方愿意沟通但时间未完全确定"],
        negative=["回款延迟", "金额或条款需要重新确认", "口头答应但到账慢"],
        anti_triggers=["比劫夺财", "财星受冲", "忌神财星较重", "合同依据不足"],
        user_visible_basis="回款类事件重点看财星、交付和合同流程是否同时被引动。",
        subtype_rules={
            "收入型": ["财星喜用", "食伤交付", "客户订单"],
            "延迟型": ["财星受冲", "流程或合同反复", "尾款未定"],
            "现金流型": ["财星", "月支事业场景", "账期推进"],
        },
    ),
    "expense": base_chain(
        ten_god_basis=["财星被耗或比劫争财时，容易对应支出、分账和临时花费。", "官杀参与时，可能表现为规则、罚款、责任成本。"],
        element_basis=["忌神引动财星时，支出更要谨慎。", "土金被引动时常见设备、资产、维修和现实物件成本。"],
        branch_basis=["年支偏家庭支出，月支偏经营工作支出，日支偏合作关系支出，时支偏项目设备支出。"],
        source_ids=["yuan_hai_zi_ping", "san_ming_tong_hui", "ming_li_tan_yuan"],
        required_patterns=["财星、比劫、官杀或忌神至少一项出现", "再结合宫位、冲动或现实资产信号"],
        supporting_patterns=["财星受冲", "比劫偏旺", "项目或家庭宫位被引动"],
        risk_patterns=["冲动消费", "隐藏成本", "人情破耗", "维修费用扩大"],
        palace_focus=["家庭、合作、项目、资产和设备支出"],
        positive=["必要设备更新", "提前处理小额成本", "把支出换成长期效率"],
        neutral=["有计划外账单或采购需求", "需要重新排预算"],
        negative=["临时破财", "维修或人情费用增加", "分账边界不清"],
        anti_triggers=["忌神参与较重", "比劫争财", "冲克过强", "预算没有凭证"],
        user_visible_basis="支出类事件不直接说破财，而是看钱流向哪里、是否必要、是否有隐藏成本。",
        subtype_rules={
            "支出型": ["财星被耗", "现实采购", "资产或维修"],
            "风险型": ["忌神", "冲动", "隐藏成本"],
            "分账型": ["比劫", "合伙", "人情分担"],
            "现金流型": ["财星受压", "账期紧", "预算重排"],
        },
    ),
    "vehicle": base_chain(
        ten_god_basis=["七杀和冲动主压力、速度、突发任务与安全边界。", "偏财可对应车辆、工具、外出成本。"],
        element_basis=["金主车辆结构、器械，火主速度和焦躁，水主流动出行。", "忌神参与时更适合做安全提醒。"],
        branch_basis=["驿马或冲动时支/月支，容易对应出行、通勤、差旅和工具检查。"],
        source_ids=["yuan_hai_zi_ping", "ming_li_tan_yuan", "yu_zhao_ding_zhen_jing"],
        required_patterns=["冲动、七杀、偏财、金火水取象至少两项共同出现"],
        supporting_patterns=["月支或时支被冲", "流月节奏急", "交通车辆类候选重复出现"],
        risk_patterns=["赶时间", "疲劳驾驶", "维修拖延", "票据保险遗漏"],
        palace_focus=["通勤、差旅、车辆、工具和路线变化"],
        positive=["提前保养避免后续麻烦", "路线规划更清楚", "出行效率提高"],
        neutral=["车辆、路线或证件需要确认", "可能有保养、保险、停车等事项"],
        negative=["维修支出", "违章罚单", "赶路导致小风险"],
        anti_triggers=["冲克过强", "忌神参与较重", "身体疲劳", "证件资料不齐"],
        user_visible_basis="车辆出行类只做安全和成本提醒，重点看冲动、速度压力和工具取象是否同时出现。",
        subtype_rules={"车辆维修": ["金象", "偏财", "冲动"], "出行支出": ["水象", "驿马/移动", "财星"]},
    ),
    "housing": base_chain(
        ten_god_basis=["印星主房屋、承载、保护和居住稳定。", "财星主资产、购买、租约和现实成本。"],
        element_basis=["土象主房屋、店铺、土地、承载和装修。", "土为忌或受冲时，容易出现维修、搬迁或环境不稳。"],
        branch_basis=["日支偏居住状态，年支偏家庭房产，月支偏店铺门面，时支偏长期添置。"],
        source_ids=["san_ming_tong_hui", "qiong_tong_bao_jian", "ming_li_tan_yuan"],
        required_patterns=["土象、印星、财星或居住宫位至少两项共同出现"],
        supporting_patterns=["土象被引动", "财星参与", "日支或年支被冲合"],
        risk_patterns=["租约合同不清", "维修成本扩大", "搬家节奏仓促"],
        palace_focus=["房屋、店铺、租约、装修、家电和大件添置"],
        positive=["适合整理居住环境", "添置实用物件", "推进房屋店铺相关事项"],
        neutral=["可能看房、换住处、维修或调整空间", "房屋店铺事项有线索，但价格、合同和时间还要确认"],
        negative=["家中维修", "搬迁反复", "大件费用超预算"],
        anti_triggers=["土象忌神", "财星受冲", "合同不清", "赶时间做决定"],
        user_visible_basis="房屋类事件重点看土象、印星、财星和居住宫位是否一起被引动。",
        subtype_rules={"房屋维修": ["土象", "印星", "冲动"], "搬家": ["日支/年支", "冲动", "租约"], "添置": ["财星", "土金", "时支"]},
    ),
    "contract": base_chain(
        ten_god_basis=["官杀主规则、审批、制度和责任。", "伤官主表达、质疑、修改和沟通摩擦。", "印星主文书、资质、盖章和凭证。"],
        element_basis=["金象主规则、条款、结构和文书边界。", "忌神或冲动参与时，合同流程更容易反复。"],
        branch_basis=["月支偏工作合同，日支偏合作协议，时支偏项目文书和交付节点。"],
        source_ids=["yuan_hai_zi_ping", "san_ming_tong_hui", "ming_li_tan_yuan"],
        required_patterns=["官杀、印星、伤官、金象或宫位流程至少两项共同出现"],
        supporting_patterns=["官印相生", "伤官见官", "月支或日支被引动"],
        risk_patterns=["条款遗漏", "审批拖延", "口头承诺替代书面", "材料错误"],
        palace_focus=["合同、审批、证照、发票税务、项目交付和合作边界"],
        positive=["条款能被梳理清楚", "流程有机会推进", "文书补齐后更稳"],
        neutral=["需要反复确认材料、金额、时间和责任", "流程可能能推进，但需要等待对方补资料或确认条款"],
        negative=["合同反复", "条款修改", "审批卡点或资料遗漏"],
        anti_triggers=["伤官见官过重", "忌神官杀", "资料遗漏", "口头承诺过多"],
        user_visible_basis="合同类事件重点看规则、文书、表达和合作宫位是否同时被引动。",
        subtype_rules={"合同反复": ["伤官", "官杀", "冲动"], "条款修改": ["金象", "印星", "日支/月支"]},
    ),
    "social": base_chain(
        ten_god_basis=["比劫主朋友同辈和圈层互动。", "食伤主表达、饭局、内容传播和销售沟通。", "财星参与时，社交容易转向资源或消费。"],
        element_basis=["桃花/人缘象配合喜用时，社交更容易带来机会。", "忌神参与时，饭局容易变成人情消耗。"],
        branch_basis=["日支引动偏一对一关系，月支引动偏职场饭局，年支引动偏旧友长辈圈层。"],
        source_ids=["yuan_hai_zi_ping", "ming_li_tan_yuan", "yu_zhao_ding_zhen_jing"],
        required_patterns=["比劫、食伤、桃花、人缘或财星至少两项共同出现"],
        supporting_patterns=["人缘象明显", "同辈星不弱", "财星或资源信号同时出现"],
        risk_patterns=["酒局过量", "人情支出", "口舌是非", "承诺太快"],
        palace_focus=["饭局、朋友、同事、客户、人情往来和资源局"],
        positive=["饭局带来资源线索", "朋友牵线", "表达沟通打开机会"],
        neutral=["有人邀约或组局，但价值需要筛选", "饭局里可能先出现信息，不一定马上变成合作"],
        negative=["酒局消耗", "人情压力", "说多做少或口舌误会"],
        anti_triggers=["忌神参与较重", "比劫夺财", "过度承诺", "酒局后驾驶或疲劳"],
        user_visible_basis="社交类事件重点看朋友同辈、表达传播、财务资源和人缘象是否一起出现。",
        subtype_rules={"饭局酒局": ["比劫", "食伤", "桃花"], "社交资源": ["财星", "转介绍", "喜用"]},
    ),
    "relationship": base_chain(
        ten_god_basis=["男命财星、女命官杀可作关系星参考。", "食伤主表达反馈，印星主安全感，比劫主边界和竞争感。"],
        element_basis=["喜用参与时，关系互动更容易正向推进。", "忌神或冲动参与时，容易有误会、节奏差或压力。"],
        branch_basis=["日支为关系和伴侣宫重点，桃花支可增加互动、人缘和情绪信号。"],
        source_ids=["yuan_hai_zi_ping", "san_ming_tong_hui", "ming_li_tan_yuan"],
        required_patterns=["关系星、夫妻宫、桃花、人缘或沟通星至少两项共同出现"],
        supporting_patterns=["日支被温和引动", "喜用参与", "关系星不弱"],
        risk_patterns=["日支受冲", "比劫过旺", "官杀压力过重", "表达误会"],
        palace_focus=["伴侣、一对一关系、暧昧推进、沟通确认和家庭介入"],
        positive=["沟通升温", "关系确认", "适合表达真实想法"],
        neutral=["互动增加，但还需要观察对方节奏", "关系有靠近信号，但仍需要现实安排配合"],
        negative=["误会解释", "节奏不一致", "家庭或现实压力介入"],
        anti_triggers=["夫妻宫受冲", "忌神关系星", "比劫竞争", "口舌误会"],
        user_visible_basis="关系类事件重点看关系星、夫妻宫、桃花和沟通状态是否一起被引动。",
        subtype_rules={"感情推进": ["关系星", "日支", "喜用"], "关系升温": ["桃花", "食伤", "沟通"]},
    ),
    "health": base_chain(
        ten_god_basis=["官杀主压力和约束，印星主恢复保护，食伤主消耗输出。", "健康只做状态提醒，不做医学判断。"],
        element_basis=["五行偏旺偏弱对应身体状态取象，忌神参与时更适合提醒作息和检查。"],
        branch_basis=["冲动时支、日支或月支时，容易影响作息、身体状态和工作压力感。"],
        source_ids=["san_ming_tong_hui", "qiong_tong_bao_jian", "ming_li_tan_yuan"],
        required_patterns=["忌神、冲动、官杀压力、五行偏旺偏弱至少两项共同出现"],
        supporting_patterns=["近期输出消耗较多", "压力星明显", "五行偏旺偏弱被流月触发"],
        risk_patterns=["熬夜", "情绪压力", "拖延复查", "过劳"],
        palace_focus=["睡眠、消化、情绪、筋骨、体检和恢复节奏"],
        positive=["适合体检复查", "适合调整作息", "小问题早处理"],
        neutral=["身体状态需要观察，不宜过度解读", "适合记录睡眠、饮食和压力变化，作为现实参考"],
        negative=["疲劳累积", "情绪波动", "小不适拖成麻烦"],
        anti_triggers=["忌神参与较重", "冲克过强", "连续过劳", "缺少现实身体信号"],
        user_visible_basis="健康类事件只作为状态管理提醒，重点看压力、五行偏差和作息消耗是否叠加；如现实身体不适明显，建议咨询专业医生。",
        subtype_rules={"身体检查": ["官杀压力", "忌神", "冲动"], "状态波动": ["五行偏差", "过劳", "情绪"]},
    ),
    "project": base_chain(
        ten_god_basis=["官杀主目标、责任、规则和考核。", "食伤主交付、表达、方案和技术输出。", "印星主资源、资料、平台和系统支持。"],
        element_basis=["喜用参与时，项目推进更容易有正反馈。", "忌神或冲动参与时，项目容易卡在流程、资源或沟通上。"],
        branch_basis=["月支为事业环境重点，时支为项目结果和长期计划重点。"],
        source_ids=["yuan_hai_zi_ping", "san_ming_tong_hui", "ming_li_tan_yuan"],
        required_patterns=["官杀、食伤、印星、月支/时支至少两项共同出现"],
        supporting_patterns=["食伤交付能力被引动", "官杀目标明确", "印星资源支持"],
        risk_patterns=["审批慢", "资源不到位", "表达和规则冲突", "承诺过多"],
        palace_focus=["项目推进、卡点突破、审批资源、团队协作和交付节点"],
        positive=["项目突破", "关键反馈出现", "进度明显推进"],
        neutral=["需要等资源、等审批或反复沟通", "项目有推进线索，但节奏可能取决于他人反馈"],
        negative=["项目卡点", "延期", "上级压力或流程阻塞"],
        anti_triggers=["伤官见官过重", "忌神官杀", "资源不足", "月支受冲"],
        user_visible_basis="项目类事件重点看目标压力、交付能力、平台资源和事业宫位是否一起被引动。",
        subtype_rules={"项目突破": ["官杀", "食伤", "喜用"], "项目卡点": ["官杀压力", "资源不足", "冲动"]},
    ),
}

TEMPLATES.update({
    "finance_income": base_chain(
        ten_god_basis=["财星主收入、客户、订单和现实回报。", "食伤主技能、内容、销售和交付，可推动财星转化。"],
        element_basis=["财星或食伤为喜用时，收入信号更容易落地。", "忌神参与时，收入可能伴随折扣、条件或延迟。"],
        branch_basis=["月支偏客户和主业收入，时支偏项目、副业和阶段成果。"],
        source_ids=["yuan_hai_zi_ping", "san_ming_tong_hui", "ming_li_tan_yuan"],
        required_patterns=["财星、食伤、喜用、事业宫位至少两项共同出现。"],
        supporting_patterns=["财星透出或数量不弱", "食伤能生财", "大运流年支持变现"],
        risk_patterns=["比劫分财", "财星受冲", "回款凭证不足"],
        palace_focus=["工资奖金、提成佣金、副业收入、客户成交和资源变现"],
        positive=["收入入口变清楚", "客户或项目带来收益线索", "奖金提成或副业收入有推进"],
        neutral=["收入消息需要等待流程确认", "金额、时间和条件仍需核对"],
        negative=["收入打折", "到账延迟", "对方临时调整条件"],
        anti_triggers=["比劫夺财", "财星受冲", "忌神财星较重", "缺少合同票据"],
        user_visible_basis="收入类事件重点看财星、交付能力和客户项目是否一起被引动。",
        subtype_rules={
            "收入型": ["财星", "食伤交付", "喜用"],
            "延迟型": ["财星受冲", "流程等待"],
            "现金流型": ["账期", "客户", "项目节点"],
        },
    ),
    "finance_delay": base_chain(
        ten_god_basis=["财星主钱款，官杀主流程约束，印星主票据和凭证。", "比劫参与时，容易出现分账、拖欠或争议。"],
        element_basis=["财星为忌或被冲时，款项更容易需要反复确认。"],
        branch_basis=["月支偏客户账期，日支偏合作结算，时支偏项目尾款。"],
        source_ids=["yuan_hai_zi_ping", "san_ming_tong_hui", "ming_li_tan_yuan"],
        required_patterns=["财星、官杀流程、印星票据、比劫分账至少两项共同出现。"],
        supporting_patterns=["合同或票据需要补齐", "项目处于收尾", "合作方反馈反复"],
        risk_patterns=["口头承诺多", "尾款条件变化", "账目不清"],
        palace_focus=["尾款、定金、账期、票据、合作结算"],
        positive=["旧账有推进空间", "补齐凭证后更容易结算"],
        neutral=["款项有消息，但仍要等流程或审批", "需要核对金额、税票和时间"],
        negative=["回款延迟", "定金尾款争议", "账目不清"],
        anti_triggers=["财星受冲", "比劫分财", "资料不全", "忌神参与较重"],
        user_visible_basis="延迟款项类事件重点看钱款、流程、凭证和合作方是否同时被引动。",
        subtype_rules={"延迟型": ["财星受冲", "官杀流程"], "分账型": ["比劫", "合作结算"], "风险型": ["账目不清", "凭证不足"]},
    ),
    "finance_expense": base_chain(
        ten_god_basis=["财星被耗主支出，比劫主分担和人情，官杀主罚款、责任和规则成本。"],
        element_basis=["土金常对应房屋、设备、车辆和维修等现实物件。", "忌神参与时，支出更需先算预算。"],
        branch_basis=["年支偏家庭支出，月支偏工作经营支出，日支偏合作支出，时支偏项目设备支出。"],
        source_ids=["yuan_hai_zi_ping", "san_ming_tong_hui", "ming_li_tan_yuan"],
        required_patterns=["财星、比劫、官杀、土金取象或冲动至少两项共同出现。"],
        supporting_patterns=["资产设备被引动", "人情局增多", "现实账单集中"],
        risk_patterns=["隐藏成本", "预算超支", "人情礼金扩大"],
        palace_focus=["大额支出、车辆费用、房屋维修、医疗体检、人情礼金"],
        positive=["提前处理必要成本", "支出换来效率或稳定性"],
        neutral=["有计划外账单，需要重新排优先级", "支出是否必要要结合现实情况逐项确认"],
        negative=["临时大额支出", "维修费用增加", "人情礼金压力"],
        anti_triggers=["忌神参与较重", "冲克过强", "比劫争财", "缺少预算"],
        user_visible_basis="支出类事件重点看钱花到哪里，以及这个支出是必要维护、责任成本还是人情消耗。",
        subtype_rules={"支出型": ["财星被耗", "现实物件"], "风险型": ["隐藏成本", "忌神"], "分账型": ["比劫", "人情"], "现金流型": ["账单集中", "预算重排"]},
    ),
    "contract_cooperation": base_chain(
        ten_god_basis=["官杀主规则、审批和合同约束，印星主文书证件和专业审查。", "财星主交易款项，比劫主合伙与分账，伤官主条款表达和规则冲突。"],
        element_basis=["金象主条款、规则和边界；忌神或冲动参与时，口头承诺更要落文字。"],
        branch_basis=["月支偏客户和工作流程，日支偏合作方，时支偏项目负责人和交付材料。"],
        source_ids=["yuan_hai_zi_ping", "san_ming_tong_hui", "ming_li_tan_yuan"],
        required_patterns=["官杀、印星、财星、比劫、伤官或合作宫位至少两项共同出现。"],
        supporting_patterns=["合同条款需要修改", "专业人士审核", "审批或材料节点被引动"],
        risk_patterns=["合作方变卦", "口头承诺不稳", "客户压价", "材料遗漏"],
        palace_focus=["合同条款、审批延迟、证件材料、定金尾款、合作边界"],
        positive=["专业审查能帮你避坑", "条款重新梳理后更清楚"],
        neutral=["合作能推进，但边界、金额和责任需要反复确认", "对方态度可能还在变化，重要内容不宜只停留在口头"],
        negative=["条款修改", "合作方临时变卦", "审批延迟或材料遗漏"],
        anti_triggers=["伤官见官过重", "资料不全", "忌神官杀", "口头承诺过多"],
        user_visible_basis="合同合作类事件重点看规则、文书、款项、合伙和表达冲突是否一起出现。",
        subtype_rules={"条款修改": ["官杀", "伤官"], "口头承诺不稳": ["食伤", "印星不足"], "合作边界": ["比劫", "日支"], "专业审查": ["印星", "官杀"]},
    ),
    "career_work": base_chain(
        ten_god_basis=["官杀主任务、职责、考核和领导压力。", "印星主平台、资料、资质和支持。", "食伤主表现、输出、方案和被看见。"],
        element_basis=["喜用参与时，事业动作更容易转成正反馈；忌神参与时，压力和反复更明显。"],
        branch_basis=["月支为事业环境，时支为项目结果，日支可看合作关系对工作的影响。"],
        source_ids=["yuan_hai_zi_ping", "san_ming_tong_hui", "ming_li_tan_yuan"],
        required_patterns=["官杀、印星、食伤、比劫、财星或月支至少两项共同出现。"],
        supporting_patterns=["任务增加", "领导关注", "团队协作或竞争增强"],
        risk_patterns=["绩效压力", "同事甩锅", "团队意见不合", "职责扩大但资源不足"],
        palace_focus=["任务、职责、领导、团队、岗位机会、绩效和面试"],
        positive=["容易被领导看见", "新岗位或面试机会出现", "项目表现有窗口"],
        neutral=["任务增加，需要重新排优先级", "机会和压力可能同时出现，需要看资源是否跟得上"],
        negative=["绩效压力", "团队意见不合", "责任扩大但支持不足"],
        anti_triggers=["忌神官杀", "比劫竞争过强", "资源不足", "月支受冲"],
        user_visible_basis="事业项目类事件重点看职责压力、资源支持、表现输出和团队关系是否一起被引动。",
        subtype_rules={"官杀压力型": ["任务增加", "绩效", "领导"], "印星支持型": ["平台", "资料", "资质"], "食伤表现型": ["汇报", "输出"], "比劫竞争型": ["团队", "同行"], "财星结果型": ["客户", "收益"]},
    ),
    "relationship_pressure": base_chain(
        ten_god_basis=["日支主亲密关系和一对一关系，财官可作关系对象星参考。", "比劫主竞争者、朋友介入和边界，食伤主表达沟通。"],
        element_basis=["喜用参与时，关系更容易靠近；忌神或冲动参与时，误会和外部压力更明显。"],
        branch_basis=["冲日支主关系波动，年支可见家庭意见，月支可见现实事业压力介入。"],
        source_ids=["yuan_hai_zi_ping", "san_ming_tong_hui", "ming_li_tan_yuan"],
        required_patterns=["日支、财官、桃花、比劫、食伤或冲日支至少两项共同出现。"],
        supporting_patterns=["沟通增加", "家庭意见介入", "旧人或第三方信号出现"],
        risk_patterns=["关系冷淡", "金钱分歧", "沟通误会", "边界不清"],
        palace_focus=["关系升温、冷淡、旧人联系、金钱分歧、家庭意见、第三方干扰"],
        positive=["伴侣支持", "结婚话题或关系确认有机会出现"],
        neutral=["互动变化明显，需要观察对方节奏", "关系议题可能和现实安排、金钱或家庭意见交织"],
        negative=["沟通误会", "关系冷淡", "家庭或第三方压力增加"],
        anti_triggers=["冲日支", "比劫竞争", "忌神关系星", "口舌误会"],
        user_visible_basis="感情关系类事件重点看日支、关系星、人缘、表达和外部压力是否一起被引动。",
        subtype_rules={"关系升温": ["财官", "桃花", "喜用"], "关系冷淡": ["忌神", "冲日支"], "金钱分歧": ["财星", "日支"], "家庭影响": ["年支", "印星"], "第三方干扰": ["比劫", "桃花"]},
    ),
    "health_lifestyle": base_chain(
        ten_god_basis=["官杀主压力和约束，食伤主消耗输出，印星主恢复保护。", "健康只作为生活状态提醒，不作医学诊断。"],
        element_basis=["五行偏旺偏弱用于观察睡眠、饮食、情绪、筋骨和恢复节奏。"],
        branch_basis=["冲动月支、日支或时支时，容易影响作息、工作压力和身体感受。"],
        source_ids=["san_ming_tong_hui", "qiong_tong_bao_jian", "ming_li_tan_yuan"],
        required_patterns=["压力、消耗、五行偏差、冲动或忌神至少两项共同出现。"],
        supporting_patterns=["作息不稳", "工作量增大", "饮食和运动节奏被打乱"],
        risk_patterns=["睡眠下降", "肠胃饮食不稳", "肩颈腰背劳损", "情绪紧绷", "运动损伤"],
        palace_focus=["睡眠、饮食、肩颈腰背、情绪、上火、眼睛疲劳、作息紊乱"],
        positive=["适合调整作息", "适合体检复查", "适合减少过度消耗"],
        neutral=["身体信号需要观察，不能仅凭命理下判断", "如果现实不适持续，建议及时咨询专业医生"],
        negative=["睡眠下降", "肠胃饮食不稳", "过劳疲惫或眼睛疲劳"],
        anti_triggers=["现实症状不明确", "证据只来自单一维度", "恐吓式表达"],
        user_visible_basis="健康类事件只做生活状态提醒，不做医学判断；如果现实不适明显，建议咨询专业医生。",
        subtype_rules={"睡眠下降": ["水火失衡", "压力"], "肠胃饮食不稳": ["土象", "食伤消耗"], "肩颈腰背劳损": ["木土金取象", "过劳"], "情绪紧绷": ["官杀压力", "火气"], "运动损伤": ["七杀", "冲动"]},
    ),
})

EVENT_TEMPLATE_MAP = {
    "nobleman_help": "nobleman",
    "mentor_advice": "nobleman",
    "resource_connection": "nobleman",
    "referral_opportunity": "nobleman",
    "platform_support": "nobleman",
    "team_support": "nobleman",
    "family_support": "nobleman",
    "hidden_help": "nobleman",
    "client_payment": "payment",
    "delayed_payment_arrival": "payment",
    "wealth_outflow": "expense",
    "asset_purchase": "housing",
    "equipment_purchase": "expense",
    "repair_expense": "expense",
    "vehicle_repair": "vehicle",
    "vehicle_expense": "vehicle",
    "travel_traffic": "vehicle",
    "home_repair": "housing",
    "rental_move": "housing",
    "shop_property": "housing",
    "property_housing": "housing",
    "contract_document": "contract",
    "approval_process": "contract",
    "document_error": "contract",
    "policy_change": "contract",
    "social_drinking": "social",
    "networking": "social",
    "favor_obligation": "social",
    "relationship_progress": "relationship",
    "peach_blossom_contact": "relationship",
    "confession_signal": "relationship",
    "medical_attention": "health",
    "health_fluctuation": "health",
    "overwork": "health",
    "project_breakthrough": "project",
    "project_delay": "project",
    "work_block": "project",
    "project_progress": "project",
}

EVENT_TEMPLATE_MAP.update({
    # 财务收入：收入型、延迟型、现金流型
    "project_income": "finance_income",
    "sales_conversion": "finance_income",
    "salary_bonus": "finance_income",
    "side_income": "finance_income",
    "resource_monetization": "finance_income",
    "commission_income": "finance_income",
    "refund_rebate": "finance_income",
    "asset_appreciation_signal": "finance_income",
    "business_cash_in": "finance_income",
    "unexpected_income": "finance_income",
    "wealth_inflow": "finance_income",
    "business_surprise": "finance_income",
    "delayed_payment_arrival": "finance_delay",
    # 财务支出：支出型、风险型、分账型、现金流型
    "cashflow_pressure": "finance_expense",
    "cooperation_money": "finance_expense",
    "debt_borrowing": "finance_delay",
    "debt_loss": "finance_delay",
    "human_cost": "finance_expense",
    "social_spending": "finance_expense",
    "investment_risk": "finance_expense",
    "family_expense": "finance_expense",
    "medical_expense_signal": "finance_expense",
    "penalty_fee": "finance_expense",
    "subscription_fee": "finance_expense",
    # 合同合作
    "legal_compliance": "contract_cooperation",
    "official_dispute": "contract_cooperation",
    "license_document": "contract_cooperation",
    "tax_invoice": "contract_cooperation",
    "insurance_claim": "contract_cooperation",
    "dispute_mediation": "contract_cooperation",
    # 事业项目
    "career_change": "career_work",
    "boss_pressure": "career_work",
    "performance_review": "career_work",
    "promotion_signal": "career_work",
    "responsibility_increase": "career_work",
    "team_conflict": "career_work",
    "colleague_support": "career_work",
    "public_expression": "career_work",
    "skill_output": "career_work",
    "workplace_reputation": "career_work",
    "resignation_thought": "career_work",
    # 感情关系
    "relationship_conflict": "relationship_pressure",
    "old_contact": "relationship_pressure",
    "emotional_distance": "relationship_pressure",
    "partner_planning": "relationship_pressure",
    "family_pressure": "relationship_pressure",
    "misunderstanding": "relationship_pressure",
    "breakup_risk_signal": "relationship_pressure",
    "marriage_discussion": "relationship_pressure",
    "value_conflict": "relationship_pressure",
    "cooperation_boundary": "relationship_pressure",
    # 健康状态
    "sleep_issue": "health_lifestyle",
    "emotional_pressure": "health_lifestyle",
    "digestion_issue": "health_lifestyle",
    "fire_anxiety": "health_lifestyle",
    "kidney_fatigue": "health_lifestyle",
    "respiratory_skin": "health_lifestyle",
    "eye_head_attention": "health_lifestyle",
    "shoulder_neck_issue": "health_lifestyle",
    "liver_gallbladder_tension": "health_lifestyle",
    "dampness_metabolism": "health_lifestyle",
})


def main() -> None:
    ontology = json.loads(ONTOLOGY_PATH.read_text(encoding="utf-8"))
    for event_type, template_name in EVENT_TEMPLATE_MAP.items():
        if event_type not in ontology:
            continue
        item = ontology[event_type]
        item.update(TEMPLATES[template_name])
    ONTOLOGY_PATH.write_text(
        json.dumps(ontology, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"updated {sum(1 for key in EVENT_TEMPLATE_MAP if key in ontology)} event evidence-chain templates")


if __name__ == "__main__":
    main()
